In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
mnist = tf.keras.datasets.mnist

TensorFlow version: 2.7.0


In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [4]:
predictions = model(x_train[:1]).numpy()
predictions


array([[ 0.13415729, -0.8643941 , -0.1953338 , -0.02725142, -0.26500484,
         0.19244874, -0.1362957 ,  0.16971597, -0.63459665, -0.675748  ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()


array([[0.13555141, 0.04993887, 0.09750073, 0.11534669, 0.09093899,
        0.14368773, 0.1034303 , 0.14045815, 0.06284033, 0.06030685]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [7]:
loss_fn(y_train[:1], predictions).numpy()


1.9401128

In [8]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])


In [9]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 11s 3ms/step - loss: 0.2916 - accuracy: 0.9165
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1412 - accuracy: 0.9575
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1063 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0870 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0755 - accuracy: 0.9762


In [10]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 1s - loss: 0.0765 - accuracy: 0.9766 - 1s/epoch - 4ms/step


[0.07647186517715454, 0.9765999913215637]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.5900877e-08, 4.0259271e-09, 5.3254489e-06, 2.9277793e-05,
        8.7361611e-12, 4.4339160e-07, 2.1214521e-14, 9.9996412e-01,
        1.1239792e-07, 5.9069936e-07],
       [4.1863154e-07, 1.5699306e-04, 9.9984062e-01, 1.0645480e-06,
        1.7220821e-15, 2.5946665e-07, 4.6039503e-07, 2.8892443e-13,
        1.5368229e-07, 3.6259947e-15],
       [9.6731185e-07, 9.9627280e-01, 2.2934811e-04, 4.4652697e-06,
        2.0975513e-04, 3.0945744e-06, 6.4331129e-05, 2.8178962e-03,
        3.9464573e-04, 2.7411600e-06],
       [9.9906558e-01, 3.5827622e-08, 2.5416107e-04, 1.0092788e-06,
        1.5487389e-05, 1.5435382e-05, 5.6604908e-06, 5.8854517e-04,
        3.4801059e-07, 5.3723783e-05],
       [4.0328869e-06, 4.5471076e-09, 3.8274604e-05, 2.7186402e-07,
        9.9757296e-01, 7.0327680e-08, 6.0252573e-06, 8.4282903e-05,
        3.0345129e-06, 2.2909828e-03]], dtype=float32)>